import type { Metadata, Viewport } from 'next'
import localFont from 'next/font/local'

import './globals.css'

import { ScrollToTop } from '@/components/ScrollToTop'
import { serializeJsonLd, websiteSchema } from '@/lib/seo'
import { SITE, canonicalOrigin, isProductionSite } from '@/lib/site'

/*
 * Neo-brutalist type trio, self-hosted as local `.woff2` files
 * (`app/fonts/`, see that folder's README + OFL.txt):
 *
 *   Archivo Black  → display headings: very heavy, very tight, no italics
 *   Space Grotesk  → body/UI: quirky geometric grotesque, variable 300–700
 *   Space Mono     → labels, tags, stats, keyboard hints
 *
 * `next/font/local` hashes + serves them from our own origin, so the build
 * never reaches out to Google Fonts (works offline and in locked-down CI),
 * no third-party request happens at runtime, and `display: swap` plus the
 * metric-aware fallback keeps CLS at 0.
 */
const archivoBlack = localFont({
  src: './fonts/archivo-black-latin-400-normal.woff2',
  weight: '400',
  style: 'normal',
  display: 'swap',
  variable: '--font-archivo',
  preload: true,
  fallback: [
    'ui-sans-serif',
    'system-ui',
    '-apple-system',
    'Segoe UI',
    'Roboto',
    'Helvetica Neue',
    'Arial',
    'sans-serif'
  ]
})

const spaceGrotesk = localFont({
  src: './fonts/space-grotesk-latin-wght-normal.woff2',
  weight: '300 700',
  style: 'normal',
  display: 'swap',
  variable: '--font-grotesk',
  preload: true,
  fallback: [
    'ui-sans-serif',
    'system-ui',
    '-apple-system',
    'Segoe UI',
    'Roboto',
    'Helvetica Neue',
    'Arial',
    'sans-serif'
  ]
})

const spaceMono = localFont({
  src: [
    { path: './fonts/space-mono-latin-400.woff2', weight: '400', style: 'normal' },
    { path: './fonts/space-mono-latin-700.woff2', weight: '700', style: 'normal' }
  ],
  display: 'swap',
  variable: '--font-mono-space',
  preload: false,
  fallback: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace']
})

/**
 * Comprehensive root metadata. Page-level `generateMetadata` in `app/page.tsx`
 * overrides the title/description for the landing page itself.
 */
export const metadata: Metadata = {
  metadataBase: new URL(canonicalOrigin),
  title: {
    default: SITE.title,
    template: `%s | ${SITE.name}`
  },
  description: SITE.description,
  applicationName: SITE.name,
  generator: `Next.js App Router · ${SITE.name}`,
  keywords: [...SITE.keywords],
  authors: [{ name: SITE.organization.name, url: canonicalOrigin }],
  creator: SITE.organization.name,
  publisher: SITE.organization.name,
  category: 'technology',
  // Served from public/site.webmanifest; makes the page installable on mobile.
  manifest: '/site.webmanifest',
  alternates: {
    canonical: '/',
    languages: {
      'x-default': `${canonicalOrigin}/`,
      en: `${canonicalOrigin}/`
    }
  },
  openGraph: {
    type: 'website',
    url: `${canonicalOrigin}/`,
    siteName: SITE.name,
    locale: SITE.locale,
    title: SITE.title,
    description: SITE.description,
    images: [
      {
        url: SITE.ogImage,
        width: 1200,
        height: 630,
        alt: `${SITE.name} — free online video downloader for 4K MP4 and MP3 from YouTube, TikTok and Instagram`
      }
    ]
  },
  twitter: {
    card: 'summary_large_image',
    title: `${SITE.name} — Free Online Video Downloader (4K MP4 & MP3)`,
    description:
      'Paste a link from YouTube, TikTok, Instagram, Facebook or X — or a TeraBox share — and download 4K/1080p/720p MP4 or MP3 audio instantly.',
    images: [{ url: SITE.ogImage, alt: `${SITE.name} downloader interface` }]
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1
    },
    ...(isProductionSite ? {} : { index: false, follow: false })
  },
  formatDetection: { telephone: false, address: false, email: false },
  other: {
    'rating': 'general',
    'slug': 'online-video-downloader'
  },
  // /icon.svg and /apple-icon.png are generated by app/icon.tsx + app/apple-icon.tsx
  // (ImageResponse), so there is no binary asset to keep in the repository.
  icons: {
    icon: [{ url: '/icon.svg', type: 'image/svg+xml', sizes: 'any' }],
    shortcut: '/icon.svg',
    apple: [{ url: '/apple-icon.png', sizes: '180x180', type: 'image/png' }]
  }
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
  // Matches `--color-paper` in app/globals.css for both themes.
  themeColor: [
    { media: '(prefers-color-scheme: dark)', color: '#0d0d14' },
    { media: '(prefers-color-scheme: light)', color: '#fff9ec' }
  ],
  colorScheme: 'dark light'
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang={SITE.language}
      className={`${archivoBlack.variable} ${spaceGrotesk.variable} ${spaceMono.variable}`}
      suppressHydrationWarning
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('download24_theme');if(t==='light'||(!t&&window.matchMedia('(prefers-color-scheme: light)').matches)){document.documentElement.classList.add('light');}else{document.documentElement.classList.add('dark');}}catch(e){}})();`
          }}
        />
        {/* Site-wide identity; the landing page adds WebApplication + FAQPage. */}
        <script
          type="application/ld+json"
          id="ld-website"
          dangerouslySetInnerHTML={{ __html: serializeJsonLd(websiteSchema()) }}
        />
      </head>
      <body className="nb-page min-h-dvh font-sans antialiased">
        <ScrollToTop />
        <a
          href="#main"
          className="nb-btn nb-btn-sun nb-btn-sm sr-only focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:z-[100]"
        >
          Skip to main content
        </a>
        <div className="relative flex min-h-dvh flex-col">{children}</div>
      </body>
    </html>
  )
}
