import type { Metadata, Viewport } from 'next'
import { Inter, Sora } from 'next/font/google'

import './globals.css'

import { ScrollToTop } from '@/components/ScrollToTop'
import { serializeJsonLd, websiteSchema } from '@/lib/seo'
import { SITE, canonicalOrigin, isProductionSite } from '@/lib/site'

/*
 * Fonts are self-hosted at build time by `next/font` (no third-party request,
 * no FOUC, and `display: swap` plus metric-aware fallback keeps CLS at 0).
 */
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
  adjustFontFallback: true,
  fallback: [
    'ui-sans-serif',
    'system-ui',
    '-apple-system',
    'Segoe UI',
    'Roboto',
    'Helvetica Neue',
    'Arial',
    'Noto Sans',
    'sans-serif'
  ]
})

const sora = Sora({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sora',
  fallback: ['ui-sans-serif', 'system-ui', 'Segoe UI', 'Roboto', 'Arial', 'sans-serif']
})

/**
 * Comprehensive root metadata. Page-level `generateMetadata` in `app/page.tsx`
 * overrides the title/description for the landing page itself.
 */
export const metadata: Metadata = {
  metadataBase: new URL(canonicalOrigin),
  title: {
    default: SITE.title,
    template: `%s | ${SITE.name}`
  },
  description: SITE.description,
  applicationName: SITE.name,
  generator: `Next.js App Router · ${SITE.name}`,
  keywords: [...SITE.keywords],
  authors: [{ name: SITE.organization.name, url: canonicalOrigin }],
  creator: SITE.organization.name,
  publisher: SITE.organization.name,
  category: 'technology',
  // Served from public/site.webmanifest; makes the page installable on mobile.
  manifest: '/site.webmanifest',
  alternates: {
    canonical: '/',
    languages: {
      'x-default': `${canonicalOrigin}/`,
      en: `${canonicalOrigin}/`
    }
  },
  openGraph: {
    type: 'website',
    url: `${canonicalOrigin}/`,
    siteName: SITE.name,
    locale: SITE.locale,
    title: SITE.title,
    description: SITE.description,
    images: [
      {
        url: SITE.ogImage,
        width: 1200,
        height: 630,
        alt: `${SITE.name} — free online video downloader for 4K MP4 and MP3 from YouTube, TikTok and Instagram`
      }
    ]
  },
  twitter: {
    card: 'summary_large_image',
    title: `${SITE.name} — Free Online Video Downloader (4K MP4 & MP3)`,
    description:
      'Paste a link from YouTube, TikTok, Instagram, Facebook or X and download 4K/1080p/720p MP4 or MP3 audio instantly.',
    images: [{ url: SITE.ogImage, alt: `${SITE.name} downloader interface` }]
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1
    },
    ...(isProductionSite ? {} : { index: false, follow: false })
  },
  formatDetection: { telephone: false, address: false, email: false },
  other: {
    'rating': 'general',
    'slug': 'online-video-downloader'
  },
  // /icon.svg and /apple-icon.png are generated by app/icon.tsx + app/apple-icon.tsx
  // (ImageResponse), so there is no binary asset to keep in the repository.
  icons: {
    icon: [{ url: '/icon.svg', type: 'image/svg+xml', sizes: 'any' }],
    shortcut: '/icon.svg',
    apple: [{ url: '/apple-icon.png', sizes: '180x180', type: 'image/png' }]
  }
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
  themeColor: SITE.themeColor,
  colorScheme: 'dark light'
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang={SITE.language} className={`${inter.variable} ${sora.variable}`} suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('download24_theme');if(t==='light'||(!t&&window.matchMedia('(prefers-color-scheme: light)').matches)){document.documentElement.classList.add('light');}else{document.documentElement.classList.add('dark');}}catch(e){}})();`
          }}
        />
        {/* Site-wide identity; the landing page adds WebApplication + FAQPage. */}
        <script
          type="application/ld+json"
          id="ld-website"
          dangerouslySetInnerHTML={{ __html: serializeJsonLd(websiteSchema()) }}
        />
      </head>
      <body className="min-h-dvh bg-ink-950 font-sans text-white/92 antialiased">
        <ScrollToTop />
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:z-[100] focus:rounded-lg focus:bg-accent focus:px-4 focus:py-2 focus:text-sm focus:font-semibold focus:text-white"
        >
          Skip to main content
        </a>
        <div className="relative flex min-h-dvh flex-col">{children}</div>
      </body>
    </html>
  )
}
